import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HomeLayout } from "./home.layout";
import { SolanaProvider } from "./_provider/solana.provider";
import { SocketProvider } from "./_api/socket";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SolanaProvider>
          <SocketProvider>
            <HomeLayout> {children}</HomeLayout>
            <Toaster position="bottom-right"></Toaster>
          </SocketProvider>
        </SolanaProvider>
      </body>
    </html>
  );
}
